apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
        color: lime
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
