apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-2-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-2
  template:
    metadata:
      labels:
        app: multi-2
        color: orange
    spec:
      initContainers:    
      - name: counter-init
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "for i in {1..15} ; do echo $i ; sleep 1; done"
      - name: homepage
        image: busybox
        args: 
        - "/bin/sh"
        - "-c"
        # Get a web page, saves it as index.html in the temp folder
        - "wget -O /work-dir/index.html http://neverssl.com/online; sleep 10;"
        volumeMounts: 
        - name: tempvol 
          mountPath: /work-dir # internal mount path        
      containers:
      - name: nginx
        image: nginx    
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: tempvol
          # location of home page for nginx
          mountPath: /usr/share/nginx/html       
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      - name: counter
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "for i in {1..999} ; do echo $i ; sleep 1; done"  
      nodeSelector:
        kubernetes.io/os: linux         
      volumes: 
      - name: tempvol
        emptyDir: {} # temp volume that only exists during the lifetime of the pod
 
